### ISSUE TITLE
训练参数需要调整吗

### ISSUE THREAD

**Issue by sunbin1993** [biubug6/Pytorch_Retinaface#115]
基于resnet50 我的结果是
    Easy   Val AP: 0.9364351140548375
    Medium Val AP: 0.9252286580463668
    Hard   Val AP: 0.7998902099430115
结果总是不够好 是有啥要注意的点吗？

**Comment by sunbin1993** [comment]
将threshold改成0.4后结果变成
Easy   Val AP: 0.9519535602939819
Medium Val AP: 0.9412768123311823
Hard   Val AP: 0.8409777216523763

是需要改threshold？

**Comment by gengyanlei** [comment]
@sunbin1993 
我验证过它的模型与mxnet源码的差异，在无后处理的同等条件下，它给出的结果是正确的。mxnet源码很高的精度是建立在复杂的后处理上步骤上，推理时间严重超时。实际应用不会像打比赛那样的。

**Comment by zehuichen123** [comment]
@sunbin1993 请问可以问下你跑的setting吗 也是4卡单bs=24吗？感觉这个正常卡塞不下啊....

**Comment by S201961152** [comment]
您好，我那个gpu显存不够，然后把batchsize改为了8，效果也是不好，请问和这个有关系吗，还是就是调参的问题

**Comment by sunbin1993** [comment]
> @sunbin1993 请问可以问下你跑的setting吗 也是4卡单bs=24吗？感觉这个正常卡塞不下啊....

我是8卡

**Comment by sunbin1993** [comment]
> 您好，我那个gpu显存不够，然后把batchsize改为了8，效果也是不好，请问和这个有关系吗，还是就是调参的问题

lr跟着改了吗

**Comment by sunbin1993** [comment]
@zehuichen123 我是8卡的batchsize=12

**Comment by S201961152** [comment]
1663678924
                            
                    
                        
                            
                                    邮箱：1663678924@qq.com
                            
                        
                
            
        在2020年12月16日 11:32，sunbin1993 写道： 



您好，我那个gpu显存不够，然后把batchsize改为了8，效果也是不好，请问和这个有关系吗，还是就是调参的问题





—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/biubug6/Pytorch_Retinaface/issues/115#issuecomment-745741542",

"url": "https://github.com/biubug6/Pytorch_Retinaface/issues/115#issuecomment-745741542",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by S201961152** [comment]
请问lr是什么，在哪里改呢         
            
                
                    
                            
                                
                            
                            
                                1663678924
                            
                    
                        
                            
                                    邮箱：1663678924@qq.com
                            
                        
                
            
        在2020年12月16日 11:32，sunbin1993 写道： 



您好，我那个gpu显存不够，然后把batchsize改为了8，效果也是不好，请问和这个有关系吗，还是就是调参的问题





—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/biubug6/Pytorch_Retinaface/issues/115#issuecomment-745741542",

"url": "https://github.com/biubug6/Pytorch_Retinaface/issues/115#issuecomment-745741542",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by S201961152** [comment]
> > 您好，我那个gpu显存不够，然后把batchsize改为了8，效果也是不好，请问和这个有关系吗，还是就是调参的问题
> 
> lr跟着改了吗

请问lr是什么，怎么改呢

**Comment by S201961152** [comment]
> > 您好，我那个gpu显存不够，然后把batchsize改为了8，效果也是不好，请问和这个有关系吗，还是就是调参的问题
> 
> lr跟着改了吗

请问lr怎么改呢，改成多少合适

**Comment by Kerr46** [comment]
> 将threshold改成0.4后结果变成
> Easy Val AP: 0.9519535602939819
> Medium Val AP: 0.9412768123311823
> Hard Val AP: 0.8409777216523763
> 
> 是需要改threshold？

请问这个threshold你是改的哪里呢
